### ISSUE TITLE
[Crash] ... Rechiseled and ConfigLib both failed to load correctly with latest version of Forge

### ISSUE THREAD

**Issue by Gamemassa** [SuperMartijn642/Rechiseled#10]
**Version Info**
- Minecraft: 1.19
- Forge: 41.0.85
- Rechiseled: 1.0.10a
- ConfigLib: 1.1.6 for MC 1.19

I tried loading ConfigLib and Rechiseled with the latest version of Forge and I got the following error messages:
![image](https://user-images.githubusercontent.com/18667108/178125670-bc2b2f04-f008-4e36-8ee1-9b9174db3889.png)

I have also attached the crash report.
[crash-2022-07-09_19.22.03-fml.txt](https://github.com/SuperMartijn642/Rechiseled/files/9078060/crash-2022-07-09_19.22.03-fml.txt)

**Comment by Gamemassa** [comment]
Config lib is working now, but I still get this error with Rechiseled:

-- Head --
Thread: Render thread
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- MOD rechiseled --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/forge/event/lifecycle/GatherDataEvent
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
		at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {}
		at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {}
		at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-6.0.0.jar%2378!/:?] {}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19-41.0.94.jar%23220!/:?] {}
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19-41.0.94.jar%23220!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19-41.0.94.jar%23220!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.94.jar%23219!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: rechiseled-1.0.10b-forge-mc1.19.jar
	Failure message: Rechiseled (rechiseled) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/forge/event/lifecycle/GatherDataEvent
	Mod Version: 1.0.10b
	Mod Issue URL: https://github.com/SuperMartijn642/Rechiseled/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.forge.event.lifecycle.GatherDataEvent
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {}
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {}
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19-41.0.94.jar%23220!/:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19-41.0.94.jar%23220!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19-41.0.94.jar%23220!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.94.jar%23219!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

[crash-2022-07-12_07.50.47-fml.txt](https://github.com/SuperMartijn642/Rechiseled/files/9092884/crash-2022-07-12_07.50.47-fml.txt)

(There are a lot of error messages in this crash report, but the Rechiseled one is right at the top)

**Comment by SuperMartijn642** [comment]
The original crash was caused by breaking changes in Forge 41.0.64. I updated both my config lib and Rechiseled to accommodate for those changes yesterday.

Today Forge pushed another update with breaking changes in 41.0.94. I have updated both my config lib and Rechiseled for those changes now as well.
It should now work with the latest versions: SuperMartijn642's Config Lib 1.1.6b, Rechiseled 1.0.10c, and Forge 41.0.94 🙂

**Comment by Gamemassa** [comment]
Yup, Rechiseled is definitely working again. Thanks so much for the fast response and support.

Btw, kinda silly that Forge changes things so frequently, eh?

**Comment by SuperMartijn642** [comment]
Great, I'll close the then.

> Btw, kinda silly that Forge changes things so frequently, eh?

Not really. The very fast updates are rather nice, since we get a lot of new or improved systems for it.
I just had awful timing when I updated everything
