### ISSUE TITLE
[Crash] Center click crashes game.

### ISSUE THREAD

**Issue by Polestar-1** [SuperMartijn642/Rechiseled#109]
1.12.2
- Minecraft
- Rechiseled
- Fusion-1.1.1-forge-mc1.12.jar
- Forge

Click middle mouse button on any block to copy it and it immediately crashes. I have no idea if its my fault or not.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Fusion Plugin (fusion-1.1.1-forge-mc1.12.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  DoubleSlabs Plugin (DoubleSlabs-1.12-0.12.2.jar)
  SuperMartijn642's Core Lib Plugin (_supermartijn642corelib-1.1.17a-forge-mc1.12.jar)
  HCASM (HammerLib-1.12.2-12.2.56.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 10/16/24 2:48 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockStone$EnumType, values=[stone, granite, smooth_granite, diorite, smooth_diorite, andesite, smooth_andesite]} as it does not exist in BlockStateContainer{block=rechiseled:andesite_polished_connecting, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at net.minecraft.block.BlockStone.func_180651_a(SourceFile:48)
	at com.supermartijn642.core.block.BaseBlock.func_180651_a(BaseBlock.java:99)
	at net.minecraft.block.Block.func_185473_a(Block.java:832)
	at net.minecraft.block.Block.getPickBlock(Block.java:1590)
	at com.supermartijn642.core.block.BaseBlock.getPickBlock(BaseBlock.java:192)
	at net.minecraftforge.common.ForgeHooks.onPickBlock(ForgeHooks.java:526)
	at net.minecraft.client.Minecraft.func_147112_ai(Minecraft.java:2604)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2259)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at net.minecraft.block.BlockStone.func_180651_a(SourceFile:48)
	at com.supermartijn642.core.block.BaseBlock.func_180651_a(BaseBlock.java:99)
	at net.minecraft.block.Block.func_185473_a(Block.java:832)
	at net.minecraft.block.Block.getPickBlock(Block.java:1590)
	at com.supermartijn642.core.block.BaseBlock.getPickBlock(BaseBlock.java:192)
	at net.minecraftforge.common.ForgeHooks.onPickBlock(ForgeHooks.java:526)
	at net.minecraft.client.Minecraft.func_147112_ai(Minecraft.java:2604)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2259)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Polestar_1'/13, l='MpServer', x=-806.24, y=23.25, z=318.15]]
	Chunk stats: MultiplayerChunkCache: 4160, 4160
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-595,22,269), Chunk: (at 13,1,13 in -38,16; contains blocks -608,0,256 to -593,255,271), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 2218605 game time, 7322 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityNewPainting['Painting++'/12, l='MpServer', x=-625.00, y=25.00, z=270.97], EntityPlayerSP['Polestar_1'/13, l='MpServer', x=-806.24, y=23.25, z=318.15]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by SuperMartijn642** [comment]
Seems to be the same as #108.
