### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by emihead** [SuperMartijn642/Rechiseled#2]
**Version Info**
- Minecraft 1.18.1
- Forge 39.0.55
- Rechiseled 1.0.6
- (Other mods in log)

**Steps to Reproduce**
- Launch the game

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/Rechiseled/files/7910072/latest.log)

**Comment by mosharky** [comment]
Same here, I believe this is the relevant error:
```
[00:47:16] [modloading-worker-0/FATAL]: Failed to load mod class Lcom/supermartijn642/rechiseled/chiseling/ChiselingRecipeLoader; for @EventBusSubscriber annotation
java.lang.ClassNotFoundException: com.supermartijn642.rechiseled.chiseling.ChiselingRecipeLoader
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[javafmllanguage-1.18.1-39.0.45.jar%23186!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.18.1-39.0.45.jar%23186!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.18.1-39.0.45.jar%23186!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.45.jar%23185!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[00:47:16] [modloading-worker-0/ERROR]: Failed to register automatic subscribers. ModID: rechiseled, class com.supermartijn642.rechiseled.Rechiseled
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.supermartijn642.rechiseled.chiseling.ChiselingRecipeLoader
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:80) ~[javafmllanguage-1.18.1-39.0.45.jar%23186!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.18.1-39.0.45.jar%23186!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.18.1-39.0.45.jar%23186!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.45.jar%23185!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.ClassNotFoundException: com.supermartijn642.rechiseled.chiseling.ChiselingRecipeLoader
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[javafmllanguage-1.18.1-39.0.45.jar%23186!/:?]
```

**Comment by SuperMartijn642** [comment]
Rechiseled 1.0.6 on Forge 39.0.55 works fine for me.

@emihead You seem to be using a lot of other mods. Could you narrow down the mods which are causing the issue?

@mosharky Are you using other mods? And if so, which other mods are you using?

**Comment by mosharky** [comment]
Here's the crash log, which should have the full list of mods at the bottom. I haven't had the time to check if the newest version (v1.0.7) has this problem still, but it definitely happens on v1.0.6 for me.

https://pastebin.com/hiGyTNmr

**Comment by SuperMartijn642** [comment]
Thank you for the crash log.
Could you try to narrow it down to fewer mods? It's a lot of effort having to download all of those mods one by one from the log.

**Comment by mosharky** [comment]
sorry, I've been quite busy! The problem's actually been fixed sometime in the last few versions, not sure if that was on your end or mine though

**Comment by SuperMartijn642** [comment]
I did change quite a lot under the hood stuff in the last few updates, so I will assume somewhere in there it got fixed.

Thank you both for reporting the issue and let me know if it happens again
