### ISSUE TITLE
[Bug] Chisel GUI does not open

### ISSUE THREAD

**Issue by onycius** [SuperMartijn642/Rechiseled#32]
**Version Info**
- Fabric 1.19.2
- 1.0.13

**Description of the Bug**
Chiseling GUI does not open after right-clicking the chisel item. Error spews out in the console. This occurs only within the mod pack, so there's probably a mod conflict.

**Error:**
[04:31:09] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2886@478edf7b, suppressing error
java.lang.IllegalArgumentException: Invalid hand null
        at net.minecraft.entity.LivingEntity.getStackInHand(LivingEntity.java:1935) ~[server-intermediary.jar:?]
        at com.supermartijn642.rechiseled.screen.ChiselContainer.getCurrentStack(ChiselContainer.java:24) ~[rechiseled-1.0.13-fabric-mc1.19.2.jar:?]
        at com.supermartijn642.rechiseled.screen.BaseChiselingContainer$1.getStack(BaseChiselingContainer.java:39) ~[rechiseled-1.0.13-fabric-mc1.19.2.jar:?]
        at net.minecraft.screen.slot.Slot.setHandler(Slot.java:2052) ~[server-intermediary.jar:?]
        at net.minecraft.screen.ScreenHandler.handler$dmh000$ledger$ledgerGiveSlotHandlerReference(ScreenHandler.java:888) ~[server-intermediary.jar:?]
        at net.minecraft.screen.ScreenHandler.addSlot(ScreenHandler.java) ~[server-intermediary.jar:?]
        at com.supermartijn642.rechiseled.screen.BaseChiselingContainer.addSlots(BaseChiselingContainer.java:30) ~[rechiseled-1.0.13-fabric-mc1.19.2.jar:?]
        at com.supermartijn642.core.gui.BaseContainer.addSlots(BaseContainer.java:34) ~[supermartijn642corelib-1.1.9d-fabric-mc1.19.2.jar:?]
        at com.supermartijn642.rechiseled.screen.BaseChiselingContainer.<init>(BaseChiselingContainer.java:25) ~[rechiseled-1.0.13-fabric-mc1.19.2.jar:?]
        at com.supermartijn642.rechiseled.screen.ChiselContainer.<init>(ChiselContainer.java:17) ~[rechiseled-1.0.13-fabric-mc1.19.2.jar:?]
        at com.supermartijn642.rechiseled.ChiselItem.use(ChiselItem.java:27) ~[rechiseled-1.0.13-fabric-mc1.19.2.jar:?]
        at net.minecraft.item.ItemStack.use(ItemStack.java:276) ~[server-intermediary.jar:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactItem(ServerPlayerInteractionManager.java:290) ~[server-intermediary.jar:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractItem(ServerPlayNetworkHandler.java:1182) ~[server-intermediary.jar:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket.apply(PlayerInteractItemC2SPacket.java:29) ~[server-intermediary.jar:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket.apply(PlayerInteractItemC2SPacket.java:7) ~[server-intermediary.jar:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:736) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:669) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Entire Log:**
https://mclo.gs/AMwbfdh

**Comment by SuperMartijn642** [comment]
Seems to be working fine with just Rechiseled installed. Both in the main hand and offhand, the chiseling gui opens as expected when right-clicking with the chisel item.
Are there any specific steps to reproduce this? Are other mods needed to reproduce this?

**Comment by Aikoyori** [comment]
I had the same problem on dedicated server on a modpack which was working before I installed a mod.

**Comment by SuperMartijn642** [comment]
Please create a new issue with the requested information.
