### ISSUE TITLE
[Crash] whenever I open the mod in 1.17.1 using the 1.17.1 version of the mod it crashes before opening the game

### ISSUE THREAD

**Issue by MikelEFG** [SuperMartijn642/Rechiseled#57]
Version I'm using
rechisled-1.14a-forge-mc1.17

crash report:
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 10/11/23, 8:47 PM
Description: Initializing game

java.lang.ExceptionInInitializerError: null
	at net.minecraft.world.item.Item.handler$zen000$getDisplayName(Item.java:529) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:mixin,re:classloading,pl:mixin:APP:structure_gel.mixins.json:ItemMixin,pl:mixin:A}
	at net.minecraft.world.item.Item.m_7626_(Item.java) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:mixin,re:classloading,pl:mixin:APP:structure_gel.mixins.json:ItemMixin,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.m_41786_(ItemStack.java:584) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:620) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.client.Minecraft.m_91316_(Minecraft.java:695) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.searchtree.ReloadableSearchTree.m_8074_(SourceFile:36) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:classloading}
	at net.minecraft.client.searchtree.ReloadableIdSearchTree.m_8080_(SourceFile:48) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$createSearchTrees$10(Minecraft.java:713) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraft.client.Minecraft.m_91271_(Minecraft.java:712) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:506) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:151) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.1.1.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.getModEventBus()" because the return value of "net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext.get()" is null
	at com.legacy.structure_gel.core.SGConfig$Common.<init>(SGConfig.java:49) ~[structure_gel-1.17.1-2.0.1.jar%23122!:2.0.1] {re:classloading}
	at net.minecraftforge.common.ForgeConfigSpec$Builder.configure(ForgeConfigSpec.java:618) ~[forge-1.17.1-37.1.1-universal.jar%23142!:?] {re:classloading}
	at com.legacy.structure_gel.core.SGConfig.<clinit>(SGConfig.java:25) ~[structure_gel-1.17.1-2.0.1.jar%23122!:2.0.1] {re:mixin,re:classloading}
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.world.item.Item.handler$zen000$getDisplayName(Item.java:529) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:mixin,re:classloading,pl:mixin:APP:structure_gel.mixins.json:ItemMixin,pl:mixin:A}
	at net.minecraft.world.item.Item.m_7626_(Item.java) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:mixin,re:classloading,pl:mixin:APP:structure_gel.mixins.json:ItemMixin,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.m_41786_(ItemStack.java:584) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:620) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.client.Minecraft.m_91316_(Minecraft.java:695) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.searchtree.ReloadableSearchTree.m_8074_(SourceFile:36) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:classloading}
	at net.minecraft.client.searchtree.ReloadableIdSearchTree.m_8080_(SourceFile:48) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$createSearchTrees$10(Minecraft.java:713) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraft.client.Minecraft.m_91271_(Minecraft.java:712) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:506) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:151) ~[client-1.17.1-20210706.113038-srg.jar%23138!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.1.1.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 610572448 bytes (582 MiB) / 1409286144 bytes (1344 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12450H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x46a3
	Graphics card #0 versionInfo: DriverVersion=31.0.101.4146
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f9d
	Graphics card #1 versionInfo: DriverVersion=31.0.15.2912
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 22196.15
	Virtual memory used (MB): 15186.57
	Swap memory total (MB): 14336.00
	Swap memory used (MB): 1264.28
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.17.1-forge-37.1.1
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: Intel(R) UHD Graphics GL version 3.2.0 - Build 31.0.101.4146, Intel
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 12x 12th Gen Intel(R) Core(TM) i5-12450H
	OptiFine Version: OptiFine_1.17.1_HD_U_H1
	OptiFine Build: 20211104-012451
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 - Build 31.0.101.4146
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 8
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.17.1-37.1.1-universal.jar                 |Forge                         |forge                         |37.1.1              |NONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90

**Comment by SuperMartijn642** [comment]
It seems to be working fine.
![image](https://github.com/SuperMartijn642/Rechiseled/assets/12382965/ca99232e-3072-4fd7-8e9a-244d355d6753)

Also please use something like [gist.github.com](http://gist.github.com) for the logs. Pasting the text like this makes it rather hard to read and it seems the mod list is cut off.
As far as I can tell from the log, nothing points to Rechiseled.

Can you narrow down the mods need to reproduce the issue?

**Comment by MikelEFG** [comment]
https://gist.github.com/MikelEFG/609c685c99267b34c3f84192a8c36205

I don't see anything pointing to the mod either but it's the only mod where if i delete it it immediately fixes the crash

**Comment by SuperMartijn642** [comment]
![image](https://github.com/SuperMartijn642/Rechiseled/assets/12382965/acaeda16-95f9-4453-82c9-eed419bdab05)
Ah the error seems to occur in a config related class from Structure Gel.

**Comment by MikelEFG** [comment]
that seemed to fix it, Thank you!
