### ISSUE TITLE
[Bug] JEI Plugin

### ISSUE THREAD

**Issue by Sunekaer** [SuperMartijn642/Rechiseled#7]
**Version Info**
jei-1.19-forge-11.0.0.206.jar
rechiseled-1.0.10-forge-mc1.19.jar

**Description of the Bug**
```
[18Jun2022 23:46:10.041] [Render thread/ERROR] [mezz.jei.common.load.PluginCaller/]: Caught an error from mod plugin: class com.supermartijn642.rechiseled.compat.jei.ChiselingJEIPlugin rechiseled:chiseling_plugin
java.lang.NoSuchMethodError: 'mezz.jei.api.gui.drawable.IDrawable mezz.jei.api.helpers.IGuiHelper.createDrawableIngredient(java.lang.Object)'
	at com.supermartijn642.rechiseled.compat.jei.ChiselingRecipeCategory.<init>(ChiselingRecipeCategory.java:32) ~[rechiseled-1.0.10-forge-mc1.19.jar%23161!/:?]
	at com.supermartijn642.rechiseled.compat.jei.ChiselingJEIPlugin.registerCategories(ChiselingJEIPlugin.java:26) ~[rechiseled-1.0.10-forge-mc1.19.jar%23161!/:?]
	at mezz.jei.common.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:137) ~[jei-1.19-forge-11.0.0.206.jar%23130!/:11.0.0.206]
	at mezz.jei.common.load.PluginCaller.callOnPlugins(PluginCaller.java:25) ~[jei-1.19-forge-11.0.0.206.jar%23130!/:11.0.0.206]
	at mezz.jei.common.load.PluginLoader.createRecipeCategories(PluginLoader.java:137) ~[jei-1.19-forge-11.0.0.206.jar%23130!/:11.0.0.206]
	at mezz.jei.common.load.PluginLoader.createRecipeManager(PluginLoader.java:164) ~[jei-1.19-forge-11.0.0.206.jar%23130!/:11.0.0.206]
	at mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:87) ~[jei-1.19-forge-11.0.0.206.jar%23130!/:11.0.0.206]
	at mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:84) ~[jei-1.19-forge-11.0.0.206.jar%23130!/:11.0.0.206]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.19-forge-11.0.0.206.jar%23130!/:11.0.0.206]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.19-forge-11.0.0.206.jar%23130!/:11.0.0.206]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1313) ~[client-1.19-20220607.102129-srg.jar%23185!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.19-20220607.102129-srg.jar%23185!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.19-20220607.102129-srg.jar%23185!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19-20220607.102129-srg.jar%23185!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19-20220607.102129-srg.jar%23185!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19-20220607.102129-srg.jar%23185!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19-20220607.102129-srg.jar%23185!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19-20220607.102129-srg.jar%23185!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1028) ~[client-1.19-20220607.102129-srg.jar%23185!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.19-20220607.102129-srg.jar%23185!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%23185!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.38.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?]
```

**Steps to Reproduce**
Launch the game and join a world look in the log

**Comment by SuperMartijn642** [comment]
Whoops, it was still just the JeiPlugin for 1.18 since JEI wasn't available for 1.19 when I updated Rechiseled 🤦‍♂️

I fixed it now in Rechiseled 1.0.10a.
Thank you for reporting the issue!
