### ISSUE TITLE
[Crash] 1.19 Rendering overlay

### ISSUE THREAD

**Issue by SvnThrSki** [SuperMartijn642/Rechiseled#8]
**Version Info**
- Minecraft, 1.19-forge-41.0.35
- Wireless Chargers, ...
- Other Mods: Framed Blocks, MrCrayFish Furniture
**Steps to Reproduce**
...

**Crash report (~/logs/latest.log)**
The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Registry Object not present: minecraft:empty
Finish Code: -1

**Comment by SuperMartijn642** [comment]
What version of Rechiseled are you using?
Could you please share the entire crash log instead of one line?
Do you have the dependencies for Rechiseled, my core and config libraries, installed?

**Comment by SvnThrSki** [comment]
I used both 1.0.10 and 1.0.10a for forge and its same crashed.
No, i dont installed anything from this, but i will try to install your core lib. Maybe, it works


---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 23.06.2022, 15:58
Description: Rendering overlay

java.lang.NullPointerException: Registry Object not present: minecraft:empty
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19-41.0.35-universal.jar%2384!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.getVanillaFluidType(ForgeHooks.java:817) ~[forge-1.19-41.0.35-universal.jar%2384!/:?] {re:classloading}
	at net.minecraft.world.level.material.Fluid.getFluidType(Fluid.java:108) ~[client-1.19-20220607.102129-srg.jar%2379!/:?] {re:classloading}
	at net.minecraftforge.client.RenderProperties.get(RenderProperties.java:57) ~[forge-1.19-41.0.35-universal.jar%2384!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.getFluidMaterials(ForgeHooksClient.java:482) ~[forge-1.19-41.0.35-universal.jar%2384!/:?] {re:classloading}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraftforge.client.ForgeHooksClient.gatherFluidTextures(ForgeHooksClient.java:477) ~[forge-1.19-41.0.35-universal.jar%2384!/:?] {re:classloading}
	at net.minecraft.client.resources.model.ModelBakery.processLoading(ModelBakery.java:205) ~[client-1.19-20220607.102129-srg.jar%2379!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.model.ForgeModelBakery.<init>(ForgeModelBakery.java:60) ~[forge-1.19-41.0.35-universal.jar%2384!/:?] {re:classloading}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:57) ~[client-1.19-20220607.102129-srg.jar%2379!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.19-20220607.102129-srg.jar%2379!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19-20220607.102129-srg.jar%2379!/:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19-41.0.35-universal.jar%2384!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.getVanillaFluidType(ForgeHooks.java:817) ~[forge-1.19-41.0.35-universal.jar%2384!/:?] {re:classloading}
	at net.minecraft.world.level.material.Fluid.getFluidType(Fluid.java:108) ~[client-1.19-20220607.102129-srg.jar%2379!/:?] {re:classloading}
	at net.minecraftforge.client.RenderProperties.get(RenderProperties.java:57) ~[forge-1.19-41.0.35-universal.jar%2384!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.getFluidMaterials(ForgeHooksClient.java:482) ~[forge-1.19-41.0.35-universal.jar%2384!/:?] {re:classloading}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.19-20220607.102129-srg.jar%2379!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1071) ~[client-1.19-20220607.102129-srg.jar%2379!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.19-20220607.102129-srg.jar%2379!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%2379!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.35.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default

**Comment by SuperMartijn642** [comment]
I believe this is an issue in Forge currently https://github.com/MinecraftForge/MinecraftForge/issues/8772, where it will crash instead of showing a message when a dependency is not installed.

Rechiseled requires both my core and config libraries.
![image](https://user-images.githubusercontent.com/12382965/175298118-dc69ef6e-aef7-4183-915d-fc4e7f4999ca.png)

**Comment by SvnThrSki** [comment]
It Works! Thank you for the answer
